# ==== These parts were generated by oTree =====
from otree.api import (
    models,
    widgets,
    BaseConstants,
    BaseSubsession,
    BaseGroup,
    BasePlayer,
    Currency as c,
    currency_range,
)


author = 'Your name here' 

doc = """
Your app description
"""


class Constants(BaseConstants):
    name_in_url = 'trust'
    players_per_group = 2
    num_rounds = 1

    endowment = c(10)
    multiplication_factor = 3


class Subsession(BaseSubsession):
    pass


class Group(BaseGroup):
    sent_amount = models.CurrencyField(label = "How much would you like to send to Player 2?", min=c(0), max=c(10))
    sent_back_amount = models.CurrencyField(label = "How much would you like to send back to Player 1?", min=c(0))

    def sent_back_amount_max(self):
        return self.sent_amount * Constants.multiplication_factor

    def set_payoffs(self):
        p1 = self.get_player_by_id(1) # Get the first player in group
        p2 = self.get_player_by_id(2) # Get the second player in group
        
        p1.payoff = Constants.endowment - self.sent_amount + self.sent_back_amount 
        p2.payoff = self.sent_amount * Constants.multiplication_factor - self.sent_back_amount
        
        
class Player(BasePlayer):
    pass
