#######################################################################################
# A default configuration that will be loaded for all jupyter books
# Users are expected to override these values in their own `_config.yml` file.
# This is also the "master list" of all allowed keys and values.

#######################################################################################
# Book settings
title                       : An introduction to oTree
author                      : Ali Seyhun Saral
copyright                   : "2020"  # Copyright year to be placed in the footer
logo                        : "./figures/base/cover.png"  # A path to the book logo
email                       : "saral@posteo.de"
exclude_patterns            : ["LICENSE.md", "installing_on_mac.md"]  # Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")

latex:
  latex_documents:
    targetname: book.tex


#######################################################################################
# Execution settings
execute:
  execute_notebooks         : auto  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  cache                     : ""  # A path to the jupyter cache that will be used to store execution artifacs. Defaults to `_build/.jupyter_cache/`
  exclude_patterns          : ["LICENSE.md", "installing_on_mac.md", "introduction/python_essentials.md"]  # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time)

#######################################################################################
# HTML-specific settings
html:
  favicon                   : "./figures/base/favicon-32x32.png"  # A path to a favicon image
  navbar_number_sections    : False  # Add a number to each section in your left navbar
#  google_analytics_id       : "UA-167881009-1"  # A GA id that can be used to track book views.
  home_page_in_navbar       : true  # Whether to include your home page in the left Navigation Bar
#  use_edit_page_button      : true  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  baseurl                   : "www.saral.it/otree"  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
#  navbar_footer_text        :
#    'You can find the files on the <a href="https://github.com/seyhunsaral/otree-book>GitHub Repository of the book</a>'
